@startuml

participant front as "FRONT"
participant controller as "Operations\ncontroller"
participant service as "Operations\nservice"
participant ipsp as "Acquiring\nservice"
participant repository as "Operations\nrepositpory"

autonumber
front -> controller: HTTP /transfer
activate controller
controller -> service: Init transaction
activate service
service -> repository: Save to log
service -> ipsp: Authorize
activate ipsp
ipsp -> ipsp: Authorized
ipsp -> front: Confirm
front -> controller: HTTP /confirm
controller -> service: Confirm

service -> ipsp: Confirm
ipsp -> ipsp: Confirm
ipsp -> ipsp: Do
ipsp -> service: Done
deactivate ipsp
service -> repository: Update in log
service -> repository: Save to logfile
service -> controller: Done
deactivate service
controller -> front: HTTP Done
deactivate controller

deactivate service
@enduml